name: dispatch repo
run-name: "${{ github.workflow }}: ${{ github.base_ref }} / ${{ github.run_number }}.${{ github.run_attempt }}"

on:
  repository_dispatch:
  push:
    branches:
      [ dev, main ]
    paths:
      - '.github/workflows/ev_dispatch_repo.yml'
      - '.github/workflows/wf_full.yml'
      - '.github/workflows/fn_build-push-docker-image.yml'
      - '.github/workflows/fn_pack-upload-artifact.yml'

defaults:
  run:
    shell: bash

jobs:
  payload:
    runs-on: ubuntu-latest

    # Map step outputs to job outputs.
    outputs:
      REPO_NAME: ${{ steps.set-output-1.outputs.TRIGGER_REPO_NAME }}
      REPO_OWNER: ${{ steps.set-output-1.outputs.TRIGGER_REPO_OWNER }}
      REF_NAME: ${{ steps.set-output-1.outputs.TRIGGER_REF_NAME }}
      ARTIFACT_NAME: ${{ steps.set-output-1.outputs.TRIGGER_ARTIFACT_NAME }}
      PROFILE: ${{ steps.set-output-2.outputs.PROFILE }}

    steps:
      - name: Received repository dispatch
        if: ${{ github.event.action != '' }}
        run: |
          echo "Event '${{ github.event.action }}' received with payload 
                      '${{ github.event.client_payload }}' from 
                      '${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repository }}'"

      - name: Set output (stage 1)
        id: set-output-1
        run: |
          echo "TRIGGER_REPO_NAME=${{ github.event.client_payload.repository || 'kodiak-web-client' }}" >> "$GITHUB_OUTPUT"
          echo "TRIGGER_REPO_OWNER=${{ github.event.client_payload.owner || 'polarlabs' }}" >> "$GITHUB_OUTPUT"
          echo "TRIGGER_REF_NAME=${{ github.event.client_payload.ref_name || 'dev' }}" >> "$GITHUB_OUTPUT"
          echo "TRIGGER_ARTIFACT_NAME=${{ github.event.client_payload.artifact_name || 'dist.tar.gz' }}" >> "$GITHUB_OUTPUT"

      - name: Set output (stage 2)
        id: set-output-2
        run: |
          if [ "${{ github.event.client_payload.ref_name }}" == "main" ]; then
            echo "PROFILE=release" >> "$GITHUB_OUTPUT"
          else
            echo "PROFILE=dev" >> "$GITHUB_OUTPUT"
          fi          

  cargo-fetch:
    uses: polarlabs/factory/.github/workflows/cargo-dep-cache.yml@v/4.0.0

  wf_full:
    uses: polarlabs/kodiak-web-server/.github/workflows/wf_full.yml@main
    needs: [ payload, cargo-fetch ]
    strategy:
      matrix:
        profiles: [ "${{ needs.payload.outputs.PROFILE }}" ]
      fail-fast: false
    with:
      DEPS_CACHE_KEY: ${{ needs.cargo-fetch.outputs.CACHE_KEY }}
      PROFILE: ${{ matrix.profiles }}
    secrets: inherit
